/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    '[id]': typeof import('./src/components/boards/[id].vue')['default']
    Board: typeof import('./src/components/Board.vue')['default']
    BoardCard: typeof import('./src/components/BoardCard.vue')['default']
    BoardCards: typeof import('./src/components/BoardCards.vue')['default']
    Boards: typeof import('./src/components/Boards.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    List: typeof import('./src/components/List.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Task: typeof import('./src/components/Task.vue')['default']
  }
}
