/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AddBoard: typeof import('./src/components/board/AddBoard.vue')['default']
    AddList: typeof import('./src/components/list/AddList.vue')['default']
    AddTask: typeof import('./src/components/task/AddTask.vue')['default']
    AppBar: typeof import('./src/components/AppBar.vue')['default']
    Board: typeof import('./src/components/board/Board.vue')['default']
    BoardCard: typeof import('./src/components/board/BoardCard.vue')['default']
    BoardCards: typeof import('./src/components/board/BoardCards.vue')['default']
    EditBoard: typeof import('./src/components/board/EditBoard.vue')['default']
    EditList: typeof import('./src/components/list/EditList.vue')['default']
    EditTask: typeof import('./src/components/task/EditTask.vue')['default']
    List: typeof import('./src/components/list/List.vue')['default']
    RemoveBoard: typeof import('./src/components/board/RemoveBoard.vue')['default']
    RemoveList: typeof import('./src/components/list/RemoveList.vue')['default']
    RemoveTask: typeof import('./src/components/task/RemoveTask.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Task: typeof import('./src/components/task/Task.vue')['default']
  }
}
